routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();
Route::get('aboutus', 'CartController@aboutus')->name('aboutus');
Route::get('/admin', 'HomeController@index')->name('admin');
Route::get('/', 'CartController@landing')->name('landing');
Route::post('/addtocart', 'CartController@store');
Route::get('/store', 'CartController@onlinestore');
Route::get('/admin/login', 'Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Auth\AdminLoginController@login')->name('admin.login.submit');
Route::post('contactform', 'HomeController@contactform');

Route::group(['middleware' => ['auth']], function() {
    Route::get('cart/step2', 'CartController@step2');
    Route::post('cart/step3', 'CartController@step3');
    Route::get('cart/step4', 'CartController@step4');
    Route::get('cart/step5', 'CartController@step5')->name('cart.step4'); //possible null route
    Route::resource('cart', 'CartController');
    Route::get('profiletransactions', 'ProfileController@profiletransactions')->name('profile.transactions'); //possible null route
    Route::get('profiletransactiondetails', 'ProfileController@profiletransactiondetails')->name('profile.transaction.details'); //possible null route
    Route::resource('profile', 'ProfileController');
    Route::get('printorder/{id}', 'CartController@printorder');
    Route::get('downloadinvoiceuser/{id}', 'CartController@downloadinvoiceuser')->name('downloadinvoiceuser');
    Route::post('profilepicture', 'ProfileController@profilepicture');

});

Route::group(['middleware' => 'auth:admin'], function() {
    Route::get('/admin', 'HomeController@index')->name('admin');
    Route::get('printinvoice/{id}', 'CartController@printinvoice');
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('admins','AdminController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('transactions', 'TransactionController');
    Route::get('patientsfortheday', 'Reports@patientsfortheday');
    Route::get('upcomingpatientbirthdays', 'Reports@upcomingpatientbirthdays');
    Route::get('reorderlevels', 'Reports@reorderlevels');
    Route::get('patientvisits', 'PatientVisits@index');
    Route::post('patientvisits', 'PatientVisits@store')->name('patientvisits.store');
    Route::get('supplementstats', 'SupplementStats@index')->name('supplementstats.index');
    Route::post('supplementstats', 'SupplementStats@store')->name('supplementstats.store');
    Route::get('top10supplements', 'Top10Supplements@index')->name('top10supplements.index');
    Route::post('top10supplements', 'Top10Supplements@store')->name('top10supplements.store');
    Route::resource('reports', 'Reports');
    Route::resource('items', 'ItemController');
    Route::get('downloadinvoice/{id}', 'TransactionController@downloadinvoice')->name('downloadinvoice');
    Route::get('import', 'MaatwebsiteController@import')->name('import');
    Route::post('importExcel', 'MaatwebsiteController@importExcel')->name('import.store');
    Route::get('approveme', 'TransactionToApproveController@store')->name('approve.store');
    Route::resource('approve', 'TransactionToApproveController');
    Route::resource('shipments', 'ShipmentsController');

});

app/Shipments.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Shipments extends Model
{
    public function transaction()
    {
        return $this->belongsTo('App\Transaction');
    }
}

app/Http/Controllers/ShipmentsController.php
<?php

namespace App\Http\Controllers;

use App\TransactionToApprove;
use App\TransactionDetail;
use Illuminate\Http\Request;
use App\Shipments;
use App\Item;
use App\Transaction;

class ShipmentsController extends Controller
{
    public function __construct(){
        $this->middleware('auth:admin');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $shipments = Shipments::all();
        return view('shipments.index', compact('shipments'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TransactionToApprove  $transactionToApprove
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $transaction = Transaction::where('id' , $id)->first();
        $transactiondetails = $transaction->details;
        return view('shipments.show', compact('transaction','transactiondetails'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TransactionToApprove  $transactionToApprove
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $transaction = Transaction::where('id', $id)->first();
        foreach ($transaction->details as $value) {
            $item = Item::where('id', $value->item_id)->first();
            $item->qtyonhand = $item->qtyonhand -$value->qty;
            $item->save();
        }
        Shipments::where('transaction_id', $id)->delete();
        return redirect()->route('shipments.index');

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\TransactionToApprove  $transactionToApprove
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TransactionToApprove $transactionToApprove)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TransactionToApprove  $transactionToApprove
     * @return \Illuminate\Http\Response
     */
    public function destroy(TransactionToApprove $transactionToApprove)
    {
        //
    }
}

resources/views/shipments/index.blade.php
@extends('layouts.app')

@section('title', '| Shipments')

@section('content')


    <nav class="breadcrumb" aria-label="breadcrumbs">
        {{ Breadcrumbs::render('shipments') }}
    </nav>
    @include('layouts.errors')
        <div class="section">
            <h3>Shipments</h3>

            <input type="text" id="SearchInput" placeholder="Search for names.." class="input">
            <table class="table is-striped is-hoverable is-fullwidth" id="searchtable">
                <thead>
                    <th>Invnumber</th>
                    <th>Date</th>
                    <th>Action</th>
                </thead>
                <tbody>
                    @foreach ($shipments as $item)

                        <tr>
                            <td>{{$item->transaction->invnumber}}</td>
                            <td>{{$item->transaction->invdate}}</td>

                            <td>
                                <a href="{{ route('shipments.show', $item->transaction_id) }}" class="button is-info is-pulled-left" style="margin-right: 3px;">Details</a>
                            </td>
                        </tr>
                    @endforeach

                </tbody>
            </table>

        </div>
@endsection

resources/views/shipments/show.blade.php
@extends('layouts.app')

@section('title', '| Shipments')

@section('content')


    <nav class="breadcrumb" aria-label="breadcrumbs">
        {{ Breadcrumbs::render('shipments') }}
    </nav>
    @include('layouts.errors')
        <div class="section">
            <h3>Shipments</h3>

            <input type="text" id="SearchInput" placeholder="Search for names.." class="input">
            <a href="{{ route('shipments.edit', $transaction->id) }}" class="button is-info is-pulled-right" style="margin-right: 3px;">Ship</a>
            <table class="table is-striped is-hoverable is-fullwidth" id="searchtable">
                <thead>
                    <th>Invnumber</th>
                    <th>Item</th>
                    <th>Descriptiton</th>
                    <th>Qty</th>

                </thead>
                <tbody>
                    @foreach ($transactiondetails as $item)

                        <tr>
                            <td>{{$item->transaction->invnumber}}</td>
                            <td>{{$item->items->first()->suppl_id}}</td>
                            <td>{{$item->items->first()->description}}</td>
                            <td>{{$item->qty}}</td>

                        </tr>
                    @endforeach

                </tbody>
            </table>

        </div>
@endsection